// Live smoke test against the real PolyDoc API in sandbox mode. For each of the
// three operations it builds the request body with the SAME buildPolydocBody
// custom function the Make modules use, POSTs it, and asserts the response is a
// 200 with the expected content type. This proves the bodies our modules
// assemble are accepted by the gateway, independent of Make's response layer.
//
// Auth: reads POLYDOC_API_KEY, else the file in POLYDOC_API_KEY_FILE, else
// /tmp/polydoc-api-token.txt. Always sends X-Sandbox: true (watermarked output,
// low ~5/sec quota), so requests are spaced out.
//
// Usage: npm run smoke   (or: POLYDOC_API_KEY=api_xxx node scripts/smoke.mjs)

import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

function loadApiKey() {
    if (process.env.POLYDOC_API_KEY) return process.env.POLYDOC_API_KEY.trim();
    const file = process.env.POLYDOC_API_KEY_FILE || '/tmp/polydoc-api-token.txt';
    if (existsSync(file)) {
        return readFileSync(file, 'utf8').trim().replace(/^Bearer\s+/i, '');
    }
    throw new Error('No API key: set POLYDOC_API_KEY or provide ' + file);
}

const fnSources = ['mergeDeep', 'buildPolydocBody']
    .map((name) => readFileSync(join(root, 'src', 'functions', name, 'code.js'), 'utf8'))
    .join('\n');
// eslint-disable-next-line no-new-func
const { buildPolydocBody } = new Function(fnSources + '\nreturn { buildPolydocBody };')();

const BASE_URL = (process.env.POLYDOC_BASE_URL || 'https://api.polydoc.tech').replace(/\/+$/, '');
const SANDBOX_SPACING_MS = 1500; // stay well under the ~5/sec sandbox limit

// Self-contained, no-JavaScript demo report. External <script>/CDN assets can
// hang the converter (playbook gotcha), so this uses inline CSS only.
const PDF_HTML = [
    '<!doctype html><html><head><meta charset="utf-8"><style>',
    'body{font-family:Arial,Helvetica,sans-serif;margin:40px;color:#222}',
    'h1{color:#4b4b4b}.bar{height:14px;background:#4b4b4b;border-radius:3px;margin:4px 0}',
    'table{width:100%;border-collapse:collapse;margin-top:16px}',
    'td,th{border-bottom:1px solid #ddd;padding:8px;text-align:left}',
    '</style></head><body>',
    '<h1>Acme Group - Portfolio Report</h1>',
    '<p>Generated by the PolyDoc Make app smoke test.</p>',
    '<div class="bar" style="width:80%"></div>',
    '<div class="bar" style="width:55%"></div>',
    '<div class="bar" style="width:30%"></div>',
    '<table><tr><th>Asset</th><th>Weight</th></tr>',
    '<tr><td>Equities</td><td>80%</td></tr>',
    '<tr><td>Bonds</td><td>55%</td></tr>',
    '<tr><td>Cash</td><td>30%</td></tr></table>',
    '</body></html>',
].join('');

const INVOICE = {
    number: 'INV-SMOKE-001',
    issueDate: '2026-06-05',
    dueDate: '2026-07-05',
    currencyCode: 'EUR',
    seller: {
        name: 'Northwind Studio GmbH',
        address: { line1: 'Hauptstrasse 1', city: 'Berlin', postalCode: '10115', countryCode: 'DE' },
        taxId: 'DE123456789',
    },
    buyer: {
        name: 'Customer SARL',
        address: { line1: 'Rue de Paix 2', city: 'Paris', postalCode: '75001', countryCode: 'FR' },
    },
    lines: [
        { description: 'Design services', quantity: 2, unitPrice: 100, lineTotal: 200, vatRate: 19, vatCategoryCode: 'S' },
    ],
    taxSummary: [{ categoryCode: 'S', rate: 19, taxableAmount: 200, taxAmount: 38 }],
    paymentTerms: 'Net 30',
    totalNetAmount: 200,
    totalTaxAmount: 38,
    totalGrossAmount: 238,
};

const CASES = [
    {
        name: 'PDF (inline HTML)',
        endpoint: '/pdf/convert',
        body: buildPolydocBody('pdf', { sourceType: 'html', html: PDF_HTML, filename: 'smoke.pdf' }),
        expectType: 'application/pdf',
    },
    {
        name: 'Screenshot (URL)',
        endpoint: '/screenshot/convert',
        body: buildPolydocBody('screenshot', {
            sourceType: 'url',
            url: 'https://example.com',
            imageType: 'png',
            fullPage: true,
        }),
        expectType: 'image/png',
    },
    {
        name: 'E-Invoice (ZUGFeRD / EN 16931)',
        endpoint: '/pdf/convert',
        body: buildPolydocBody('einvoice', {
            sourceType: 'html',
            html: '<h1>Invoice ' + INVOICE.number + '</h1>',
            eInvoiceStandard: 'zugferd',
            eInvoiceProfile: 'en16931',
            eInvoiceVerify: true,
            invoice: INVOICE,
        }),
        expectType: 'application/pdf',
    },
];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function run() {
    const apiKey = loadApiKey();
    let failures = 0;

    for (let i = 0; i < CASES.length; i++) {
        const c = CASES[i];
        if (i > 0) await sleep(SANDBOX_SPACING_MS);
        try {
            const res = await fetch(BASE_URL + c.endpoint, {
                method: 'POST',
                headers: {
                    'content-type': 'application/json',
                    authorization: 'Bearer ' + apiKey,
                    'x-sandbox': 'true',
                },
                body: JSON.stringify(c.body),
            });
            const contentType = (res.headers.get('content-type') || '').split(';')[0].trim();
            const buf = Buffer.from(await res.arrayBuffer());
            const ok = res.status === 200 && contentType === c.expectType;
            if (!ok) failures++;
            const detail = [
                'status=' + res.status,
                'type=' + (contentType || 'none'),
                'bytes=' + buf.length,
                'conversion=' + (res.headers.get('x-conversion-id') || '-'),
                'credit=' + (res.headers.get('x-credit-used') || '-'),
            ].join(' ');
            console.log((ok ? 'PASS' : 'FAIL') + '  ' + c.name + '  (' + detail + ')');
            if (!ok && contentType.startsWith('application/json')) {
                console.log('      body: ' + buf.toString('utf8').slice(0, 400));
            }
        } catch (err) {
            failures++;
            console.log('FAIL  ' + c.name + '  (' + err.message + ')');
        }
    }

    console.log('');
    console.log(failures === 0 ? 'All smoke checks passed.' : failures + ' smoke check(s) failed.');
    process.exit(failures === 0 ? 0 : 1);
}

run();
